name: 'PR Bouncer'
description: Bounce pull requests that are too big
author: 'oncilla'
inputs:
  github-token:
    description: |
      Secret github token: secrets.GITHUB_TOKEN
    required: true
  warning-size:
    description: |
      Number of added lines that cause warning.

      If the number of added lines of code exceed this threshold,
      a warning message is added to the pull request.

      Generated files are excluded from this rule.
    required: false
    default: '750'
  bounce-size:
    description: |
      Number of added lines that cause pull request to be rejected.

      If the number of added lines of code exceed this threshold,
      an error message is added to the pull request, and it is automatically
      closed. This can be turned of by specifying the ignore label on the pull
      request.
    required: false
    default: '1000'
  ignore-label:
    description: |
      Label to instruct bouncer to ignore the pull request.

      If this label is specified, the PR bouncer does not automatically closed
      the pull request.
    required: false
    default: 'no-bounce'
  file-excluders:
    description: |
      Regular expressions that matches file paths to exclude.

      All files with a path that is matched by any of the regular expression,
      are excluded from counting towards the additions.

      The format is a comma separated list.
    required: false
    default: '_test.go,\/mock_,BUILD.bazel'
  generated-markers:
    description: |
      Grepable file markers for generated files.

      All files that contain any of the markers, are excluded from counting
      towards the additions.

      The format is a comma separated list. The files are checked using
      'grep', thus, the marker need to be formatted accordingly.
    required: false
    default: 'GENERATED FILE DO NOT EDIT,Code generated by .* DO NOT EDIT'
  auto-close:
    description: |
      Automatically close pull request if it exceeds the bounce-size.
    required: false
    default: 'false'
  warning-message:
    description: |
      Message to be posted as warning on big pull requests.
    required: false
    default: |
      Thank you for the contribution.

      The pull request is rather big. It exceeds {WARNING-SIZE} additions of
      code. Please consider splitting the pull request into multiple
      contribution to make the review process easier.
  bounce-message:
    description: |
      Message to be posted on bounced pull requests.
    required: false
    default: |
      Thank you for the contribution.

      The pull request exceeds {BOUNCE-SIZE} of allowed additions. Please
      consider splitting the pull request into multiple contributions to make
      the review process easier for both you and the maintainer.

      If this pull request absolutely needs to be this big, contact a maintainer
      and they can whitelist this PR,
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'crosshair'
  color: 'orange'
